Added error handling to dsh

diff --git a/dsh b/dsh
--- a/dsh
+++ b/dsh
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+set -o errexit
+
+program=`basename $0`
+
+if [ $# -lt 1 ]
+then
+  echo "Invalid number of arguments: $#"
+  echo "Usage: $program pattern"
+  exit 1
+fi
+
 linecount=$(docker ps |grep $1| wc -l)
 if [[ $linecount != 1 ]]; then
   echo 'Error, multiple matching containers'
